// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"doubleX rmmv autobattle bugfix v100a","status":true,"description":"Lets you fixes leaked side effects bugs when an autobattle\r\nactor has skills/items with damage formulae having side effects","parameters":{"isEnabled":"\"return true;\"","sideEffectFreeDmgFormula":"\"return dmgFormula.replace(new RegExp('.*[};] *', 'gim'), '');\""}},
{"name":"DoubleX RMMV Superlative ATB Params v000a","status":true,"description":"The parameter plugin of DoubleX RMMV Superlative ATB","parameters":{"_isParamFuncCached":"false","_isNoteCached":"true","_isAlwaysRecacheAllSwitchVars":"false","IsCoreEnabled":"\"return true;\"","_coreBaseFillUnit":"coreBaseFillATBFrame","coreBaseFillATBFrame":"\"return 600;\"","coreBaseFillATBSec":"\"return 5.0;\"","_coreTurnUnit":"coreTurnATBTime","coreTurnATBTime":"\"return baseFillATB * 2.0;\"","coreTurnATBAct":"\"return BattleManager.allBattleMembers().length * 2;\"","canCoreTurnClockOverflow":"\"return false;\"","coreMaxATBVal":"\"return 100.0;\"","_coreMaxATBValNoteChainingRule":"/","_coreMaxATBValNotePriorities":"[\"states\",\"armors\",\"weapons\",\"class\",\"actor\",\"enemy\"]","_coreActStateNoteChainingRule":"some"}},
{"name":"DoubleX RMMV Superlative ATB Cfgs v000a","status":true,"description":"The configuration plugin of DoubleX RMMV Superlative ATB","parameters":{}},
{"name":"DoubleX RMMV Superlative ATB Impl v000a","status":true,"description":"The implementation plugin of DoubleX RMMV Superlative ATB","parameters":{}},
{"name":"DoubleX RMMV Superlative ATB Unit Tests v000a","status":true,"description":"The unit test plugin of DoubleX RMMV Superlative ATB","parameters":{}},
{"name":"DoubleX RMMV Superlative ATB Docs v000a","status":true,"description":"To be the most flexible, performant and powerful ATB system\r\nframework with the greatest amount of freedom while being user-friendly","parameters":{}}
];
