// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DoubleX RMMV Superlative ATB Params v100a","status":true,"description":"The parameter plugin of DoubleX RMMV Superlative ATB","parameters":{"_isCached":"true","_isAlwaysRecacheAllSwitchVars":"false","IsCoreEnabled":"\"return $gameSwitches.value(1);\"","_coreBaseFillUnit":"coreBaseFillATBSec","coreBaseFillATBFrame":"\"return 600;\"","coreBaseFillATBSec":"\"return 5.0;\"","_coreTurnUnit":"coreTurnATBTime","coreTurnATBTime":"\"return baseFillATB * 2.0;\"","coreTurnATBAct":"\"return BattleManager.allBattleMembers().length;\"","canCoreTurnClockOverflow":"\"return false;\"","coreMaxATBVal":"\"return 100.0;\"","_coreMaxATBValNoteChainingRule":"/","_coreMaxATBValNotePriorities":"[\"states\", \"armors\",\"weapons\",\"class\",\"actor\",\"enemy\"]","_coreActStateNoteChainingRule":"*"}},
{"name":"DoubleX RMMV Superlative ATB Cfgs v100a","status":true,"description":"The configuration plugin of DoubleX RMMV Superlative ATB","parameters":{}},
{"name":"DoubleX RMMV Superlative ATB Impl v100a","status":true,"description":"The implementation plugin of DoubleX RMMV Superlative ATB","parameters":{}},
{"name":"DoubleX RMMV Superlative ATB Docs v100a","status":true,"description":"To be the most flexible, performant and powerful RMMV ATB system\r\nframework with the greatest amount of freedom while being user-friendly","parameters":{}}
];
